from PyQt5 import QtCore, QtGui, QtWidgets
from logic import MainLogic


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setObjectName("calculate")
        self.gridLayout_2.addWidget(self.calculate, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 0, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 5, 1, 1, 1)
        self.kvadrati = QtWidgets.QRadioButton(self.main)
        self.kvadrati.setObjectName("kvadrati")
        self.shape_group = QtWidgets.QButtonGroup(MainWindow)
        self.shape_group.setObjectName("shape_group")
        self.shape_group.addButton(self.kvadrati)
        self.gridLayout_3.addWidget(self.kvadrati, 4, 1, 1, 1)
        self.trapecia = QtWidgets.QRadioButton(self.main)
        self.trapecia.setObjectName("trapecia")
        self.shape_group.addButton(self.trapecia)
        self.gridLayout_3.addWidget(self.trapecia, 3, 1, 1, 1)
        self.samkutxedi = QtWidgets.QRadioButton(self.main)
        self.samkutxedi.setObjectName("samkutxedi")
        self.shape_group.addButton(self.samkutxedi)
        self.gridLayout_3.addWidget(self.samkutxedi, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 2, 0, 1, 1)
        self.wre = QtWidgets.QRadioButton(self.main)
        self.wre.setAutoExclusive(True)
        self.wre.setObjectName("wre")
        self.shape_group.addButton(self.wre)
        self.gridLayout_3.addWidget(self.wre, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 2, 1, 1)
        self.select = QtWidgets.QPushButton(self.main)
        self.select.setObjectName("select")
        self.gridLayout_3.addWidget(self.select, 5, 2, 1, 1)
        self.stackedWidget.addWidget(self.main)
        self.kvadrati_page = QtWidgets.QWidget()
        self.kvadrati_page.setObjectName("kvadrati_page")
        self.kvadrati_sigrdze = QtWidgets.QDoubleSpinBox(self.kvadrati_page)
        self.kvadrati_sigrdze.setGeometry(QtCore.QRect(280, 90, 151, 41))
        self.kvadrati_sigrdze.setObjectName("kvadrati_sigrdze")
        self.label_13 = QtWidgets.QLabel(self.kvadrati_page)
        self.label_13.setGeometry(QtCore.QRect(150, 90, 111, 31))
        self.label_13.setObjectName("label_13")
        self.kvadrati_area_2 = QtWidgets.QLCDNumber(self.kvadrati_page)
        self.kvadrati_area_2.setGeometry(QtCore.QRect(270, 260, 64, 23))
        self.kvadrati_area_2.setObjectName("kvadrati_area_2")
        self.kvadrati_area_3 = QtWidgets.QLCDNumber(self.kvadrati_page)
        self.kvadrati_area_3.setGeometry(QtCore.QRect(270, 300, 64, 23))
        self.kvadrati_area_3.setObjectName("kvadrati_area_3")
        self.label_14 = QtWidgets.QLabel(self.kvadrati_page)
        self.label_14.setGeometry(QtCore.QRect(160, 250, 111, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.kvadrati_page)
        self.label_15.setGeometry(QtCore.QRect(160, 290, 111, 31))
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.kvadrati_page)
        self.samkutxedi_page = QtWidgets.QWidget()
        self.samkutxedi_page.setObjectName("samkutxedi_page")
        self.label_4 = QtWidgets.QLabel(self.samkutxedi_page)
        self.label_4.setGeometry(QtCore.QRect(150, 16, 71, 31))
        self.label_4.setObjectName("label_4")
        self.samkutxedi_gverdi1 = QtWidgets.QDoubleSpinBox(self.samkutxedi_page)
        self.samkutxedi_gverdi1.setGeometry(QtCore.QRect(280, 10, 151, 41))
        self.samkutxedi_gverdi1.setObjectName("samkutxedi_gverdi1")
        self.label_5 = QtWidgets.QLabel(self.samkutxedi_page)
        self.label_5.setGeometry(QtCore.QRect(150, 70, 71, 31))
        self.label_5.setObjectName("label_5")
        self.samkutxedi_gverdi2 = QtWidgets.QDoubleSpinBox(self.samkutxedi_page)
        self.samkutxedi_gverdi2.setGeometry(QtCore.QRect(280, 60, 151, 41))
        self.samkutxedi_gverdi2.setObjectName("samkutxedi_gverdi2")
        self.label_6 = QtWidgets.QLabel(self.samkutxedi_page)
        self.label_6.setGeometry(QtCore.QRect(150, 120, 71, 31))
        self.label_6.setObjectName("label_6")
        self.samkutxedi_gverdi3 = QtWidgets.QDoubleSpinBox(self.samkutxedi_page)
        self.samkutxedi_gverdi3.setGeometry(QtCore.QRect(280, 110, 151, 41))
        self.samkutxedi_gverdi3.setObjectName("samkutxedi_gverdi3")
        self.label_7 = QtWidgets.QLabel(self.samkutxedi_page)
        self.label_7.setGeometry(QtCore.QRect(260, 270, 101, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.samkutxedi_page)
        self.label_8.setGeometry(QtCore.QRect(260, 320, 111, 17))
        self.label_8.setObjectName("label_8")
        self.samkutxedi_fartobi = QtWidgets.QLCDNumber(self.samkutxedi_page)
        self.samkutxedi_fartobi.setGeometry(QtCore.QRect(390, 270, 64, 23))
        self.samkutxedi_fartobi.setObjectName("samkutxedi_fartobi")
        self.samkutxedi_perimeter = QtWidgets.QLCDNumber(self.samkutxedi_page)
        self.samkutxedi_perimeter.setGeometry(QtCore.QRect(390, 320, 64, 23))
        self.samkutxedi_perimeter.setObjectName("samkutxedi_perimeter")
        self.stackedWidget.addWidget(self.samkutxedi_page)
        self.wre_page = QtWidgets.QWidget()
        self.wre_page.setObjectName("wre_page")
        self.radiusi = QtWidgets.QDoubleSpinBox(self.wre_page)
        self.radiusi.setGeometry(QtCore.QRect(220, 30, 151, 41))
        self.radiusi.setObjectName("radiusi")
        self.label = QtWidgets.QLabel(self.wre_page)
        self.label.setGeometry(QtCore.QRect(126, 36, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.wre_page)
        self.label_2.setGeometry(QtCore.QRect(130, 200, 121, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.wre_page)
        self.label_3.setGeometry(QtCore.QRect(130, 260, 67, 17))
        self.label_3.setObjectName("label_3")
        self.wre_fartobi = QtWidgets.QLCDNumber(self.wre_page)
        self.wre_fartobi.setGeometry(QtCore.QRect(230, 200, 64, 23))
        self.wre_fartobi.setObjectName("wre_fartobi")
        self.wre_sigrdze = QtWidgets.QLCDNumber(self.wre_page)
        self.wre_sigrdze.setGeometry(QtCore.QRect(230, 260, 64, 23))
        self.wre_sigrdze.setObjectName("wre_sigrdze")
        self.stackedWidget.addWidget(self.wre_page)
        self.trapecia_page = QtWidgets.QWidget()
        self.trapecia_page.setObjectName("trapecia_page")
        self.zeda_fudze = QtWidgets.QDoubleSpinBox(self.trapecia_page)
        self.zeda_fudze.setGeometry(QtCore.QRect(260, 60, 151, 41))
        self.zeda_fudze.setObjectName("zeda_fudze")
        self.label_9 = QtWidgets.QLabel(self.trapecia_page)
        self.label_9.setGeometry(QtCore.QRect(110, 60, 111, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.trapecia_page)
        self.label_10.setGeometry(QtCore.QRect(110, 110, 111, 31))
        self.label_10.setObjectName("label_10")
        self.qveda_fudze = QtWidgets.QDoubleSpinBox(self.trapecia_page)
        self.qveda_fudze.setGeometry(QtCore.QRect(260, 110, 151, 41))
        self.qveda_fudze.setObjectName("qveda_fudze")
        self.trapeci_area = QtWidgets.QLCDNumber(self.trapecia_page)
        self.trapeci_area.setGeometry(QtCore.QRect(230, 240, 64, 23))
        self.trapeci_area.setObjectName("trapeci_area")
        self.trapecia_perimeter = QtWidgets.QLCDNumber(self.trapecia_page)
        self.trapecia_perimeter.setGeometry(QtCore.QRect(230, 280, 64, 23))
        self.trapecia_perimeter.setObjectName("trapecia_perimeter")
        self.label_11 = QtWidgets.QLabel(self.trapecia_page)
        self.label_11.setGeometry(QtCore.QRect(100, 240, 101, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.trapecia_page)
        self.label_12.setGeometry(QtCore.QRect(100, 280, 101, 17))
        self.label_12.setObjectName("label_12")
        self.trapecia_ferdi = QtWidgets.QDoubleSpinBox(self.trapecia_page)
        self.trapecia_ferdi.setGeometry(QtCore.QRect(260, 160, 151, 41))
        self.trapecia_ferdi.setObjectName("trapecia_ferdi")
        self.label_16 = QtWidgets.QLabel(self.trapecia_page)
        self.label_16.setGeometry(QtCore.QRect(110, 160, 111, 31))
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.trapecia_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.logic = MainLogic(self)
        # circle change events
        self.radiusi.textChanged.connect(self.logic.radius)
        # triangle change events
        self.samkutxedi_gverdi1.textChanged.connect(self.logic.triangle_side1)
        self.samkutxedi_gverdi2.textChanged.connect(self.logic.triangle_side2)
        self.samkutxedi_gverdi3.textChanged.connect(self.logic.triangle_side3)
        # square change events
        self.kvadrati_sigrdze.textChanged.connect(self.logic.square_size)
        # trapezoid change events
        self.zeda_fudze.textChanged.connect(self.logic.trapezoid_upper_length)
        self.qveda_fudze.textChanged.connect(self.logic.trapezoid_lower_length)
        self.trapecia_ferdi.textChanged.connect(self.logic.trapezoid_side_length)
        #
        self.shape_group.buttonClicked.connect(self.logic.select_shape)
        self.calculate.clicked.connect(self.logic.calculate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculate.setText(_translate("MainWindow", "გამოთვლა"))
        self.back.setText(_translate("MainWindow", "უკან დაბრუნება"))
        self.kvadrati.setText(_translate("MainWindow", "კვადრატი"))
        self.trapecia.setText(_translate("MainWindow", "ტოლფერდა ტრაპეცია"))
        self.samkutxedi.setText(_translate("MainWindow", "სამკუთხედი"))
        self.wre.setText(_translate("MainWindow", "წრე"))
        self.select.setText(_translate("MainWindow", "არჩევა"))
        self.label_13.setText(_translate("MainWindow", "სიგრძე"))
        self.label_14.setText(_translate("MainWindow", "პერიმეტრი"))
        self.label_15.setText(_translate("MainWindow", "ფართობი"))
        self.label_4.setText(_translate("MainWindow", "გვერდი1"))
        self.label_5.setText(_translate("MainWindow", "გვერდი2"))
        self.label_6.setText(_translate("MainWindow", "გვერდი3"))
        self.label_7.setText(_translate("MainWindow", "ფართობი"))
        self.label_8.setText(_translate("MainWindow", "პერიმეტრი"))
        self.label.setText(_translate("MainWindow", "რადიუსი"))
        self.label_2.setText(_translate("MainWindow", "ფართობი"))
        self.label_3.setText(_translate("MainWindow", "სიგრძე"))
        self.label_9.setText(_translate("MainWindow", "პატარა ფუძე"))
        self.label_10.setText(_translate("MainWindow", "დიდი ფუძე"))
        self.label_11.setText(_translate("MainWindow", "ფართობი"))
        self.label_12.setText(_translate("MainWindow", "პერიმეტრი"))
        self.label_16.setText(_translate("MainWindow", "ფერდი"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
